/* Generated by tools/build.mjs. Do not edit by hand. */
window.ZOE_CONFIG = {
  "formEndpoint": "https://script.google.com/macros/s/AKfycbytoV9xN3J79pHvXy67VMONMc8MXwC5vf5DuwdrSyxy8ej0BwUGLe92KMmsjZimQNeu/exec",
  "newsletterEndpoint": "https://script.google.com/macros/s/AKfycbytoV9xN3J79pHvXy67VMONMc8MXwC5vf5DuwdrSyxy8ej0BwUGLe92KMmsjZimQNeu/exec",
  "bookingUrl": "https://calendar.app.google/Uj9v44HE72kJrKz8A",
  "paidBookingUrl": null,
  "coursesUrl": null,
  "courses": {
    "singleDating": null,
    "committed": null,
    "engagedFirstYear": null,
    "couplesBundle": null,
    "claimEndpoint": null
  },
  "giving": {
    "stripe": null,
    "paypal": null
  },
  "payments": {
    "devotional": {
      "amazon": null,
      "etsy": null,
      "gumroad": null,
      "stripe": null,
      "paypal": null
    },
    "journal": {
      "amazon": null,
      "etsy": null,
      "gumroad": null,
      "stripe": null,
      "paypal": null
    }
  },
  "resources": {
    "channelUrl": "https://www.youtube.com/@zoefamilylife",
    "playlists": [
      {
        "id": "PLTiUnmAGHZkM",
        "title": "Roadmap from Single to Married",
        "embedUrl": "https://www.youtube-nocookie.com/embed/videoseries?list=PLTiUnmAGHZkM"
      },
      {
        "id": "PL2QfJI8adA_YfcMZByFKFitwv59m6iDnP",
        "title": "Recognizing the Right One",
        "embedUrl": "https://www.youtube-nocookie.com/embed/videoseries?list=PL2QfJI8adA_YfcMZByFKFitwv59m6iDnP"
      },
      {
        "id": "PL2QfJI8adA_YOC37FdaYA0rCaTSNbyyk-",
        "title": "Dangerous Lies Singles Believe and The Truth that Nullifies Them",
        "embedUrl": "https://www.youtube-nocookie.com/embed/videoseries?list=PL2QfJI8adA_YOC37FdaYA0rCaTSNbyyk-"
      },
      {
        "id": "PL2QfJI8adA_YXHB-JjLXv7qyP2pbetI0Z",
        "title": "Marriage 101",
        "embedUrl": "https://www.youtube-nocookie.com/embed/videoseries?list=PL2QfJI8adA_YXHB-JjLXv7qyP2pbetI0Z"
      },
      {
        "id": "PL2QfJI8adA_Zlr6yymbp_MkVfb0tO9cze",
        "title": "Recipes for a Blessed Marriage",
        "embedUrl": "https://www.youtube-nocookie.com/embed/videoseries?list=PL2QfJI8adA_Zlr6yymbp_MkVfb0tO9cze"
      },
      {
        "id": "PL2QfJI8adA_b13X9wl5zwxWDyeO5pCkK2",
        "title": "Conflict Resolution",
        "embedUrl": "https://www.youtube-nocookie.com/embed/videoseries?list=PL2QfJI8adA_b13X9wl5zwxWDyeO5pCkK2"
      }
    ]
  }
};
