/**
 * Build-time integration tests for Zoe Life.
 *   node tests/check-build.mjs
 *
 * Proves that ordinary rebuilds keep live endpoints, marketplace URLs are
 * https-only, and buy-link attributes are escaped.
 */

import { spawnSync } from "node:child_process";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  LIVE_DEFAULTS,
  buyButtonsHtml,
  escapeAttr,
  httpsOnly,
  resolveIntegrations,
} from "../tools/site-config.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const BUILD = join(ROOT, "tools/build.mjs");

let pass = 0;
const failures = [];

function check(name, ok, detail) {
  if (ok) {
    pass++;
    console.log(`  ok   ${name}`);
  } else {
    failures.push(`${name}${detail ? ` :: ${detail}` : ""}`);
    console.log(`  FAIL ${name}${detail ? ` :: ${detail}` : ""}`);
  }
}

function group(title) {
  console.log(`\n${title}`);
}

function zoeEnv(extra = {}) {
  const env = { ...process.env };
  for (const key of Object.keys(env)) {
    if (key.startsWith("ZOE_")) delete env[key];
  }
  Object.assign(env, extra);
  return env;
}

function writeConfig(dir, cfg) {
  mkdirSync(join(dir, "js"), { recursive: true });
  writeFileSync(
    join(dir, "js/config.js"),
    `/* Generated by tools/build.mjs. Do not edit by hand. */\nwindow.ZOE_CONFIG = ${JSON.stringify(cfg, null, 2)};\n`
  );
}

function readConfig(dir) {
  const text = readFileSync(join(dir, "js/config.js"), "utf8");
  return JSON.parse(text.slice(text.indexOf("{"), text.lastIndexOf("}") + 1));
}

function runBuild(dir, { args = [], env = {} } = {}) {
  return spawnSync(process.execPath, [BUILD, ...args], {
    cwd: ROOT,
    env: zoeEnv({ ZOE_BUILD_ROOT: dir, ...env }),
    encoding: "utf8",
  });
}

function emptyPayments() {
  return {
    devotional: { amazon: null, etsy: null, gumroad: null, stripe: null, paypal: null },
    journal: { amazon: null, etsy: null, gumroad: null, stripe: null, paypal: null },
  };
}

const PRESERVED = {
  formEndpoint: "https://example.com/preserve-form",
  newsletterEndpoint: "https://example.com/preserve-newsletter",
  bookingUrl: "https://example.com/preserve-booking",
  payments: emptyPayments(),
};

/* ----------------------------------------------------------- helpers -- */
group("HTTPS validation");

check("httpsOnly accepts an https URL", httpsOnly("https://example.com/ok", "test") === "https://example.com/ok");
check("httpsOnly treats empty as null", httpsOnly("  ", "test") === null && httpsOnly(null, "test") === null);

for (const bad of ["http://example.com/nope", "javascript:alert(1)", "ftp://example.com/file"]) {
  let threw = false;
  try {
    httpsOnly(bad, "ZOE_AMAZON_DEVOTIONAL_URL");
  } catch (err) {
    threw = /https|valid URL/i.test(err.message);
  }
  check(`httpsOnly rejects ${bad}`, threw);
}

let httpsKept = true;
try {
  httpsOnly("https://example.com", "ok");
} catch {
  httpsKept = false;
}
check("httpsOnly does not reject a plain https URL", httpsKept);

let httpNull = null;
try {
  httpNull = httpsOnly("http://example.com/nope", "test", { invalid: "null" });
} catch {
  httpNull = "threw";
}
check("httpsOnly can fail-closed to null", httpNull === null);

group("Attribute escaping");

const dirty = 'https://example.com/buy?q="onclick&x=<script>';
const escaped = escapeAttr(dirty);
check("escapeAttr encodes double quotes", escaped.includes("&quot;") && !escaped.includes('"'));
check("escapeAttr encodes ampersands", escaped.includes("&amp;"));
check("escapeAttr encodes angle brackets", escaped.includes("&lt;") && escaped.includes("&gt;"));

const buttonHtml = buyButtonsHtml({
  amazon: dirty,
  etsy: null,
  gumroad: null,
  stripe: null,
  paypal: null,
});
check("Buy button href is escaped", buttonHtml.includes(`href="${escaped}"`));
check("Unescaped quote never appears inside the href attribute", !/href="[^"]*"[^"]*onclick/.test(buttonHtml));
check("Buy button does not emit a raw <script> into the attribute", !buttonHtml.includes("<script>"));

group("Resolve without env");

const preserved = resolveIntegrations({ env: {}, existing: PRESERVED, staging: false });
check("Ordinary build keeps existing formEndpoint", preserved.formEndpoint === PRESERVED.formEndpoint);
check("Ordinary build keeps existing newsletterEndpoint", preserved.newsletterEndpoint === PRESERVED.newsletterEndpoint);
check("Ordinary build keeps existing bookingUrl", preserved.bookingUrl === PRESERVED.bookingUrl);

const stagedExisting = resolveIntegrations({ env: {}, existing: PRESERVED, staging: true });
check("Staging still preserves existing live endpoints", stagedExisting.formEndpoint === PRESERVED.formEndpoint);
check("Staging still preserves existing booking URL", stagedExisting.bookingUrl === PRESERVED.bookingUrl);

const stagedEmpty = resolveIntegrations({ env: {}, existing: {}, staging: true });
check("Staging fail-closes form when nothing to preserve", stagedEmpty.formEndpoint === null);
check("Staging fail-closes newsletter when nothing to preserve", stagedEmpty.newsletterEndpoint === null);
check("Staging fail-closes booking when nothing to preserve", stagedEmpty.bookingUrl === null);

const ordinaryEmpty = resolveIntegrations({ env: {}, existing: {}, staging: false });
check("Ordinary empty config falls back to live FormSubmit", ordinaryEmpty.formEndpoint === LIVE_DEFAULTS.formEndpoint);
check("Ordinary empty config falls back to live booking", ordinaryEmpty.bookingUrl === LIVE_DEFAULTS.bookingUrl);

const overridden = resolveIntegrations({
  env: { ZOE_FORM_ENDPOINT: "https://example.com/override-form" },
  existing: PRESERVED,
  staging: false,
});
check("Env overrides existing formEndpoint", overridden.formEndpoint === "https://example.com/override-form");
check("Env override leaves other existing endpoints", overridden.bookingUrl === PRESERVED.bookingUrl);

check("Marketplace links stay null until provided", preserved.payments.devotional.amazon === null);
check("Stripe stays null until provided", preserved.payments.journal.stripe === null);

let marketThrew = false;
try {
  resolveIntegrations({
    env: { ZOE_ETSY_JOURNAL_URL: "javascript:alert(1)" },
    existing: PRESERVED,
    staging: false,
  });
} catch (err) {
  marketThrew = /https/i.test(err.message);
}
check("javascript: marketplace env is rejected", marketThrew);

let httpMarketThrew = false;
try {
  resolveIntegrations({
    env: { ZOE_GUMROAD_DEVOTIONAL_URL: "http://example.com/gumroad" },
    existing: PRESERVED,
    staging: false,
  });
} catch (err) {
  httpMarketThrew = /https/i.test(err.message);
}
check("http:// marketplace env is rejected", httpMarketThrew);

const marketOk = resolveIntegrations({
  env: { ZOE_AMAZON_DEVOTIONAL_URL: "https://example.com/devotional" },
  existing: PRESERVED,
  staging: false,
});
check("https marketplace env is accepted", marketOk.payments.devotional.amazon === "https://example.com/devotional");
check("Unset marketplace sibling stays null", marketOk.payments.devotional.etsy === null);

const comingSoon = buyButtonsHtml(emptyPayments().devotional);
check("No buy links keep purchase-coming copy", /purchase-coming/.test(comingSoon) && /Purchase options coming/.test(comingSoon));

/* ---------------------------------------------- spawn rebuild -- */
group("Rebuild without env preserves existing endpoints");

const tmpPreserve = mkdtempSync(join(tmpdir(), "zoe-preserve-"));
try {
  writeConfig(tmpPreserve, PRESERVED);
  const result = runBuild(tmpPreserve);
  check("Ordinary rebuild without env exits 0", result.status === 0, result.stderr || result.stdout.slice(-400));
  const next = readConfig(tmpPreserve);
  check("Rebuilt formEndpoint was not wiped", next.formEndpoint === PRESERVED.formEndpoint);
  check("Rebuilt newsletterEndpoint was not wiped", next.newsletterEndpoint === PRESERVED.newsletterEndpoint);
  check("Rebuilt bookingUrl was not wiped", next.bookingUrl === PRESERVED.bookingUrl);
  check("Marketplace URLs remain unset", next.payments.devotional.amazon === null && next.payments.journal.gumroad === null);
  const books = readFileSync(join(tmpPreserve, "books.html"), "utf8");
  check("Books stay purchase-coming when marketplaces are unset", /purchase-coming/.test(books));
  check("Preserved rebuild did not invent Amazon/Etsy/Gumroad hosts", !/amazon\.com|etsy\.com|gumroad\.com/i.test(books));
} finally {
  rmSync(tmpPreserve, { recursive: true, force: true });
}

const tmpStaging = mkdtempSync(join(tmpdir(), "zoe-staging-"));
try {
  writeConfig(tmpStaging, {
    formEndpoint: null,
    newsletterEndpoint: null,
    bookingUrl: null,
    payments: emptyPayments(),
  });
  const result = runBuild(tmpStaging, { args: ["--staging"] });
  check("Staging rebuild with empty config exits 0", result.status === 0, result.stderr || result.stdout.slice(-400));
  const next = readConfig(tmpStaging);
  check("Staging rebuild without existing values stays fail-closed", next.formEndpoint === null && next.bookingUrl === null);
} finally {
  rmSync(tmpStaging, { recursive: true, force: true });
}

group("Marketplace spawn validation and escaping");

const tmpHttp = mkdtempSync(join(tmpdir(), "zoe-http-"));
try {
  writeConfig(tmpHttp, PRESERVED);
  const result = runBuild(tmpHttp, { env: { ZOE_AMAZON_DEVOTIONAL_URL: "http://example.com/amazon" } });
  check("Build rejects http marketplace URL", result.status !== 0);
  check("http rejection mentions https", /https/i.test(result.stderr + result.stdout));
} finally {
  rmSync(tmpHttp, { recursive: true, force: true });
}

const tmpJs = mkdtempSync(join(tmpdir(), "zoe-js-"));
try {
  writeConfig(tmpJs, PRESERVED);
  const result = runBuild(tmpJs, { env: { ZOE_ETSY_JOURNAL_URL: "javascript:alert(1)" } });
  check("Build rejects javascript: marketplace URL", result.status !== 0);
} finally {
  rmSync(tmpJs, { recursive: true, force: true });
}

const tmpEsc = mkdtempSync(join(tmpdir(), "zoe-esc-"));
try {
  writeConfig(tmpEsc, PRESERVED);
  const href = 'https://example.com/buy?q="onclick&x=<img>';
  const result = runBuild(tmpEsc, { env: { ZOE_GUMROAD_DEVOTIONAL_URL: href } });
  check("Build accepts an https marketplace URL with reserved characters", result.status === 0, result.stderr);
  const books = readFileSync(join(tmpEsc, "books.html"), "utf8");
  const expected = escapeAttr(href);
  check("Generated Books HTML escapes the buy href", books.includes(`href="${expected}"`));
  check("Generated Books HTML does not break out of the href attribute", !books.includes('href="https://example.com/buy?q="onclick'));
  check("Buy on Gumroad button is shown when that URL is set", /Buy on Gumroad/.test(books));
  check("Journal stays purchase-coming when only the devotional has a link", 
    (books.match(/purchase-coming/g) || []).length === 1);
} finally {
  rmSync(tmpEsc, { recursive: true, force: true });
}

console.log(`\n${"=".repeat(60)}`);
if (failures.length) {
  console.log(`FAILED: ${failures.length} check(s), ${pass} passed\n`);
  failures.forEach((f) => console.log(`  - ${f}`));
  process.exit(1);
}
console.log(`PASSED: all ${pass} checks`);
